apiVersion: v1
kind: Service
metadata:
  name: mongodb-external
  namespace: wiz-exercise
spec:
  ports:
    - port: 27017
      targetPort: 27017
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mongodb-external
  namespace: wiz-exercise
subsets:
  - addresses:
      - ip: MONGODB_HOST_IP
    ports:
      - port: 27017
